services:
  db:
    image: postgres
    restart: always
    ports:
      - '3003:5432'
    volumes:
      - ./db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=games
  web:
    build:
      context: /www/sudoku
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    image: result/latest