networks:
  proxiable_network:
    name: proxiable
    external: true

services:
  web:
    build:
      context: /www/sudoku
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    image: result/latest
    networks:
      - proxiable_network
